language: R
sudo: false
cache: packages
r_github_packages: 
- metrumresearchgroup/covrpage
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: IgnELCvSBoP1fkYbDKogJnDzRWRFVqFjIT/GUuW1Yd/I+bbs57GzRIQegRqjhVwutpgznxWXfFB+5s+6aKU2SObZbPZ1th4bUY4JWmFBwT1nsSMbFOVHWmEjL317X69lz/B/BMdrS/ldwysmOSiAM9zKofv943UvikCktiXGjcLClOOeqgxuWHz5uN/3md/aAblny57oybiLfcUh1op06Vq8F3Anym4HDNPuglojUyaJwYh6KPypSrj9GSQdFdStq3njuQKpC1g00mnVCZwTC/8NKzsLWialT62RXi2uklBEdEa6wU8WtqvsVddAiUrC3GtR1+AEQ4i/8DrJJgcSbNCnVBR0CJf71O4R6XNO1z7gXZIK6OqOoZWtS+TOc5lvvPluNLUIhN2XUSLUWopumFfhJXgzOibUI3eNtHAiQcPK+78hKYBuC4MQdSOTzhoSr+BLGaFVfmBVZd8Mq20MEJYMICNvIcjZzpvY+8t/iTKaFvzvpeK0pqcVfvOYh+dhkLPj0wi7SaGDd0jGQK6JkDiTbWRzO2eY2W51Vi+lTBV0lH8OgObYO/cNVPXhmzogB3l1D73FK2z3dEmQ4zQ2NbM2rQE3ewp0pWgx73s2ogZoek8TRpxEDy6lMaGJHC35r52C77a3SMeh7rz5Znu2lkH78B+JpXCB8p9CQOnX8pk=
