language: R
sudo: false
cache: packages
r_github_packages: 
- metrumresearchgroup/covrpage   
- metrumresearchgroup/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: IgnELCvSBoP1fkYbDKogJnDzRWRFVqFjIT/GUuW1Yd/I+bbs57GzRIQegRqjhVwutpgznxWXfFB+5s+6aKU2SObZbPZ1th4bUY4JWmFBwT1nsSMbFOVHWmEjL317X69lz/B/BMdrS/ldwysmOSiAM9zKofv943UvikCktiXGjcLClOOeqgxuWHz5uN/3md/aAblny57oybiLfcUh1op06Vq8F3Anym4HDNPuglojUyaJwYh6KPypSrj9GSQdFdStq3njuQKpC1g00mnVCZwTC/8NKzsLWialT62RXi2uklBEdEa6wU8WtqvsVddAiUrC3GtR1+AEQ4i/8DrJJgcSbNCnVBR0CJf71O4R6XNO1z7gXZIK6OqOoZWtS+TOc5lvvPluNLUIhN2XUSLUWopumFfhJXgzOibUI3eNtHAiQcPK+78hKYBuC4MQdSOTzhoSr+BLGaFVfmBVZd8Mq20MEJYMICNvIcjZzpvY+8t/iTKaFvzvpeK0pqcVfvOYh+dhkLPj0wi7SaGDd0jGQK6JkDiTbWRzO2eY2W51Vi+lTBV0lH8OgObYO/cNVPXhmzogB3l1D73FK2z3dEmQ4zQ2NbM2rQE3ewp0pWgx73s2ogZoek8TRpxEDy6lMaGJHC35r52C77a3SMeh7rz5Znu2lkH78B+JpXCB8p9CQOnX8pk=
notifications:
  slack:
    secure: YDWEobNljHKrq1H+Ejw2s1BX1KGnuI1tATejJ6STXITiStzXvh9OhuNi02yIB0wHI+JGkHMKgKk3SeBingDSzI9weL4ZadGJUO/L9lzfiRCGnzxm+tqchUZNOBX1aFnBi9Aek0ERQjYSgpml0ZdR9BQ2y98yQvb6+yxeefIePPKAon8ZB2npKOtkRGXJC5HNja8sizp3d4k/SEGd7g/J4Jz60F5UHjWzjtBzXTX1AKYUtFLBXj0BQH3uZvWSYHd+fCYqbj8HYtDcmOacFYoXsktSEYhpU1TBT9WB/O4i6VICm89Khfu3h18lFvFFgQA654rjBcNA+RNz9KLUg/4W5KaV2O91ialjgJ/Uy/X0IOEogjIG4ypKH2N/5/l0xHlRRJMYa9dcaPoXTrY0RXPNenDKAotClF/ue01GLa661fcX8LO8WlRSjEjg+zcil06QG9DIzpN8yFutoHFKXkDgdDmbf1niYsN46T28lcNvPelgBY0/tISM6hUGl2J4Jx3mBdmiHUXcRXvXHzS6PGw+CmQb5HqfTnop7+mJBr9sDowTKbBRSF09ge4keU7CFzXQZtUyOIzfh+BTS48BhcvnwH8P2hbzcnryeSBD06H1Y9oAsazGD/3deMDY4IDS1D3RFvouj2tr63KWYFGYcj6lWLoRbYZIOdVPGGhjI3zGeW8=
